name: Process OpenAPI Files

on:
  push:
    branches:
      - prod
    paths:
      - 'openapi/**'  # Trigger action only when files in the ./openapi folder or its subdirectories change
  workflow_dispatch: # Allows the action to be triggered manually

jobs:
  process_openapi_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq nodejs npm

    - name: Install Mintlify Scrape
      run: npm install @mintlify/scraping@latest -g

    - name: Verify OpenAPI Files Directory
      run: |
        if [ ! -d "./openapi" ]; then
          echo "Directory './openapi' does not exist."
          exit 1
        fi

        echo "Files in ./openapi/:"
        ls ./openapi/

    - name: Run OpenAPI processing script
      run: |
        output_array=()

        for file in ./openapi/*.yaml; do
          if [ ! -f "$file" ]; then
            echo "No OpenAPI files found."
            exit 1
          fi

          filename=$(basename "$file" .spec.yaml)
          mkdir -p "$filename"
          cd ./$filename

          command_output=$(mintlify-scrape openapi-file ../$file | tail -n +2)

          ls -la
          
          merged_pages=$(echo "$command_output" | jq -s '[.[][] | .pages[]]')

          if ! jq -e . >/dev/null 2>&1 <<<"$merged_pages"; then
            echo "Invalid JSON in merged_pages" >&2
            exit 1
          fi

          output=$(jq -n --argjson pages "$merged_pages" --arg filename "$filename" '{"group": $filename, "pages": $pages}')
          
          # Append output to array
          output_array+="$output,"

          cd ../
        done
        
        # Remove the last comma and close the array
        output_array="${output_array%,}]"

        # Print the array
        echo "$output_array"

        # Set the output array as an output variable
        echo "mint_output=$output_array" >> "$GITHUB_OUTPUT"

  update_mint_json:
    runs-on: ubuntu-latest
    needs: process_openapi_files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace placeholder in mint.json.tpl
        env:
          MINT_OUTPUT: ${{ needs.process_openapi_files.outputs.mint_output }}
        run: |          
          # Create the mint.json from mint.json.tpl
          sed "s|{{REPLACE_HERE}}|$MINT_OUTPUT|" mint.json.tpl > mint.json.new
          
          # Delete the old mint.json if it exists
          if [ -f "mint.json" ]; then
            rm -f mint.json
          fi
          
          cat mint.json.new
          
          # Move the new mint.json to the correct location
          mv mint.json.new mint.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mint.json
          git commit -m "Update mint.json with new OpenAPI data"
          git push origin main