name: Replace Placeholder in mint.json.tpl

on:
  push:
    branches:
      - prod

jobs:

  set-output:
    runs-on: ubuntu-latest
    outputs:
      json_array: ${{ steps.set-output-step.outputs.json_array }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq nodejs npm

      - name: Install Mintlify Scrape
        run: npm install @mintlify/scraping@latest -g

      - name: Run OpenAPI processing script
        run: |
          output_array=()
          
          for file in ./openapi/*.yaml; do
            if [ ! -f "$file" ]; then
             echo "No OpenAPI files found."
             exit 1
            fi
  
            filename=$(basename "$file" .spec.yaml)
            mkdir -p "$filename"
            cd ./$filename
  
            command_output=$(mintlify-scrape openapi-file ../$file | tail -n +2)
  
            ls -la
            
            merged_pages=$(echo "$command_output" | jq -s '[.[][] | .pages[]]')
  
            if ! jq -e . >/dev/null 2>&1 <<<"$merged_pages"; then
             echo "Invalid JSON in merged_pages" >&2
             exit 1
            fi
  
            output=$(jq -n --argjson pages "$merged_pages" --arg filename "$filename" '{"group": $filename, "pages": $pages}')
            
            # Append output to array
            output_array+=("$output")
          
            cd ../
          done
          
          # Remove the last comma and close the array
          echo "${output_array[@]}" > | jq ".[0:] | .[]"

  replace-placeholder:
    runs-on: ubuntu-latest
    needs: set-output
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Replace Placeholder in mint.json.tpl
        run: |
          json_array='${{ needs.set-output.outputs.json_array }}'
          jq --argjson arr "$json_array" '
          .navigation[] | 
          if .group == "Benzinga APIs" then 
            .pages += [$arr[] | .pages[]]
          else 
            . 
          end' mint.json.tpl > minty.json
          cat minty.json
